@echo off
title Archi
REM Archi startup script (generated by install.py)
set "ARCHI_ROOT=%~dp0.."
cd /d "%ARCHI_ROOT%"

REM --- Prerequisite checks ---
if not exist "%ARCHI_ROOT%\venv\Scripts\python.exe" (
    echo [ERROR] Python venv not found at %ARCHI_ROOT%\venv\Scripts\python.exe
    echo Run: python -m venv venv ^&^& venv\Scripts\python.exe scripts\install.py deps
    pause
    exit /b 1
)

if not exist "%ARCHI_ROOT%\scripts\start.py" (
    echo [ERROR] start.py not found at %ARCHI_ROOT%\scripts\start.py
    pause
    exit /b 1
)

if not exist "%ARCHI_ROOT%\.env" (
    echo [WARNING] .env file not found. Copy .env.example to .env and configure API keys.
)

REM --- Create logs dir if missing ---
if not exist "%ARCHI_ROOT%\logs" mkdir "%ARCHI_ROOT%\logs"

REM --- Launch Archi ---
echo Starting Archi (watchdog mode)...
"%ARCHI_ROOT%\venv\Scripts\python.exe" "%ARCHI_ROOT%\scripts\start.py" watchdog
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Archi exited with error code %ERRORLEVEL%.
    pause
    exit /b %ERRORLEVEL%
)
